name: Syntroper Diagrams

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hassasif-syntroper/readme-analyzer@main
        with:
          api_url: "https://a292-103-39-83-176.ngrok-free.app"
          paths: |
            README.md
          rewrite_mode: managed_blocks
          commit_changes: "true"
